'use client'
import {useEffect,useMemo,useState} from 'react'

type News={id:string;title:string;url:string;source:string;publishedAt:string;excerpt?:string;evidence?:string;kind?:string;titleZh?:string;excerptZh?:string}
type Excerpt={id:string;text:string;charCount:number}
type Meta={id:string;bodyAvailable:boolean;bodyChars:number;excerpts:Excerpt[]}

const nav=[['news','News Radar'],['threads','Threads 工坊'],['audit','Audit'],['sources','Sources'],['settings','Settings']] as const

export default function Home(){
 const [section,setSection]=useState<(typeof nav)[number][0]>('news')
 const [news,setNews]=useState<News[]>([]); const [selected,setSelected]=useState<string[]>([]); const [loading,setLoading]=useState(false); const [err,setErr]=useState('')
 const [style,setStyle]=useState('news'); const [format,setFormat]=useState('single'); const [sourceMode,setSourceMode]=useState('compact'); const [focus,setFocus]=useState('balanced'); const [hashtags,setHashtags]=useState(true)
 const [draft,setDraft]=useState(''); const [posts,setPosts]=useState<string[]>([]); const [postIndex,setPostIndex]=useState(0); const [meta,setMeta]=useState<Meta[]>([])
 const [excerptLoading,setExcerptLoading]=useState<string[]>([]); const [copied,setCopied]=useState('')
 const [search,setSearch]=useState('')

 const loadNews=async()=>{setLoading(true);setErr('');try{const r=await fetch('/api/news');const j=await r.json();if(!r.ok)throw new Error(j.errors?.[0]||'news request failed');setNews(j.items||[]);if(j.errors?.length)setErr(`部分來源失敗：${j.errors.slice(0,2).join('、')}`)}catch(e){setErr(e instanceof Error?e.message:String(e))}finally{setLoading(false)}}
 useEffect(()=>{void loadNews()},[])
 const visible=useMemo(()=>news.filter(n=>{const q=search.trim().toLowerCase();return !q||n.title.toLowerCase().includes(q)||n.source.toLowerCase().includes(q)}),[news,search])
 const chosen=useMemo(()=>news.filter(n=>selected.includes(n.id)),[news,selected])
 const toggle=(id:string)=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id])
 const selectVisible=()=>setSelected([...new Set([...selected,...visible.map(n=>n.id)])])
 const clear=()=>setSelected([])
 const translateAll=async()=>{if(!news.length)return; const r=await fetch('/api/translate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({articles:news.map(n=>({id:n.id,title:n.title,excerpt:n.excerpt||''}))})}); const j=await r.json(); if(j.translations?.length)setNews(old=>old.map(n=>{const t=j.translations.find((x:any)=>x.id===n.id);return t?{...n,titleZh:t.titleZh,excerptZh:t.excerptZh}:n}))}
 const generate=async()=>{setSection('threads');setDraft('生成中…');setPosts([]);setPostIndex(0);setMeta([]);const r=await fetch('/api/threads',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({style,format,sourceMode,contentFocus:focus,hashtags,articles:chosen.map(n=>({id:n.id,source:n.source,link:n.url,titleOriginal:n.title,titleZh:n.titleZh,excerptOriginal:n.excerpt,excerptZh:n.excerptZh}))})});const j=await r.json();setPosts(j.posts||[]);setDraft(j.posts?.[0]||j.error||'未產生草稿');setMeta(j.sourceMeta||[])}
 const loadExcerpt=async(id:string,url:string)=>{if(meta.find(m=>m.id===id))return;setExcerptLoading(x=>[...x,id]);try{const r=await fetch('/api/article-extract',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url})});const j=await r.json();setMeta(x=>[...x,{id,bodyAvailable:!!j.bodyAvailable,bodyChars:Number(j.bodyChars||0),excerpts:j.excerpts||[]}])}finally{setExcerptLoading(x=>x.filter(v=>v!==id))}}
 const getMeta=(id:string)=>meta.find(m=>m.id===id)
 const copy=async(id:string,text:string)=>{await navigator.clipboard.writeText(text);setCopied(id);setTimeout(()=>setCopied(''),1200)}
 const copyAll=async()=>{const blocks: string[]=[];for(const n of chosen){const m=getMeta(n.id);if(!m?.bodyAvailable)continue;for(const ex of m.excerpts)blocks.push(`【${n.source}】\n${ex.text}`)}if(blocks.length){await navigator.clipboard.writeText(blocks.join('\n\n'));setCopied('all');setTimeout(()=>setCopied(''),1200)}}
 return <div className="shell">
  <header className="header"><div className="brand">GAME MEDIA DAILY<small>Editorial OS · GitHub / Vercel migration starter</small></div><nav className="nav">{nav.map(([id,label])=><button key={id} className={section===id?'active':''} onClick={()=>setSection(id)}>{label}</button>)}</nav></header>
  <main className="wrap">
   <div className="topbar"><div><h1 className="title">{section==='news'?'News Radar':section==='threads'?'Threads 工坊':section==='audit'?'Audit':section==='sources'?'Sources':'Settings'}</h1><div className="subtitle">新聞 → 原文擷取 → 證據／來源 → 翻譯 → Threads</div></div><div className="controls"><span className="status good">Vercel-ready</span><button className="btn" onClick={()=>void loadNews()} disabled={loading}>{loading?'讀取中…':'重新抓新聞'}</button></div></div>
   {section==='news'&&<div className="grid"><div className="card"><h2>新聞雷達</h2><div className="controls"><input className="control" placeholder="搜尋標題／來源" value={search} onChange={e=>setSearch(e.target.value)}/><button className="btn" onClick={selectVisible}>全選目前結果</button><button className="btn" onClick={clear}>清除選取</button><button className="btn" onClick={()=>void translateAll()}>全量翻譯</button><button className="btn primary" disabled={!selected.length} onClick={()=>void generate()}>送到 Threads（{selected.length}）</button></div>{err&&<div className="footerNote">{err}</div>}<div className="newsList">{visible.map(n=><article key={n.id} className={`news ${selected.includes(n.id)?'selected':''}`}><div className="newsTop"><input className="check" type="checkbox" checked={selected.includes(n.id)} onChange={()=>toggle(n.id)}/><div style={{flex:1}}><h3>{n.titleZh||n.title}</h3>{n.titleZh&&<div className="small">原文：{n.title}</div>}<div className="meta"><span className="tag">{n.source}</span><span className="tag">{n.evidence||'E3'}</span><span>{new Date(n.publishedAt).toLocaleString('zh-TW')}</span></div><div className="tools"><a className="btn" href={n.url} target="_blank" rel="noreferrer">閱讀原文</a><button className="btn" onClick={()=>void loadExcerpt(n.id,n.url)}>載入長段原文</button></div></div></div></article>)}{!visible.length&&<div className="empty">沒有符合條件的新聞</div>}</div></div><aside className="card"><h2>選取摘要</h2><div className="small">選取新聞後送進 Threads 工坊；原文長段落仍保持「原文」狀態，不混入 AI 草稿。</div><div className="newsList">{chosen.map(n=><div key={n.id} className="story"><div className="storyTitle">{n.title}</div><div className="small">{n.source} · {n.evidence||'E3'}</div></div>)}</div></aside></div>}
   {section==='threads'&&<div className="threads"><aside className="card"><h2>已選新聞</h2><div className="storylist">{chosen.map(n=><div className="story" key={n.id}><div className="storyTitle">{n.titleZh||n.title}</div><div className="small">{n.source} · {n.evidence||'E3'}</div><button className="btn" style={{marginTop:8}} onClick={()=>void loadExcerpt(n.id,n.url)}>{excerptLoading.includes(n.id)?'擷取中…':'載入原文重點'}</button></div>)}{!chosen.length&&<div className="empty">先回 News Radar 勾選新聞</div>}</div></aside><section className="card"><h2>貼文草稿</h2><div className="optionGrid"><select className="control" value={style} onChange={e=>setStyle(e.target.value)}><option value="news">新聞</option><option value="casual">玩家口吻</option><option value="analysis">分析</option><option value="data">數據</option></select><select className="control" value={format} onChange={e=>setFormat(e.target.value)}><option value="single">單篇</option><option value="thread">2–5 則 Thread</option></select><select className="control" value={focus} onChange={e=>setFocus(e.target.value)}><option value="headline">偏標題</option><option value="balanced">平衡</option><option value="body">偏內文</option></select><select className="control" value={sourceMode} onChange={e=>setSourceMode(e.target.value)}><option value="none">不附來源</option><option value="compact">簡潔來源</option><option value="full">完整來源</option></select></div><div className="controls"><label className="small"><input type="checkbox" checked={hashtags} onChange={e=>setHashtags(e.target.checked)}/> Hashtags</label><button className="btn primary" disabled={!chosen.length} onClick={()=>void generate()}>生成／重生</button>{posts.length>1&&<><button className="btn" onClick={()=>{const i=Math.max(0,postIndex-1);setPostIndex(i);setDraft(posts[i])}}>上一則</button><button className="btn" onClick={()=>{const i=Math.min(posts.length-1,postIndex+1);setPostIndex(i);setDraft(posts[i])}}>下一則</button></>}</div><textarea className="draft" value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Threads 草稿會出現在這裡…"/><div className="footerNote">目前貼文 API 只會用提供給它的內容；若原文抓取失敗，會標示為僅 RSS 摘要，不能假裝讀完全文。</div><h2 style={{marginTop:22}}>原文重點摘錄</h2><div className="controls"><button className="btn" onClick={()=>void copyAll()} disabled={!meta.some(m=>m.excerpts.length)}>{copied==='all'?'已複製':'複製全部原文重點'}</button></div>{chosen.map(n=>{const m=getMeta(n.id);return <div key={n.id} className="excerptGrid"><div className="small">{n.source} · {m?m.bodyAvailable?`原文內文 ${m.bodyChars} 字`:'僅 RSS 摘要':'尚未載入原文'}</div>{m?.bodyAvailable?m.excerpts.map(ex=><div className="excerpt" key={ex.id}><div className="excerptMeta"><span className="small">原文段落 · 約 {ex.charCount} 字</span><button className="btn" onClick={()=>void copy(`${n.id}:${ex.id}`,ex.text)}>{copied===`${n.id}:${ex.id}`?'已複製':'複製這段'}</button></div><div className="excerptText">{ex.text}</div></div>):m?<div className="empty">此來源目前只能取得 RSS／摘要，沒有可安全呈現的完整內文。</div>:null}</div>})}</section></div>}
   {section==='audit'&&<div className="card"><h2>Audit（遷移骨架）</h2><p className="subtitle">保留你原本的 Truth / Evidence / Claim / Risk / Editorial Gate 概念。第一階段先把現有流程搬上 Next.js，第二階段再把完整 hard rules / checks 接入資料庫。</p><pre style={{whiteSpace:'pre-wrap',color:'#b8ccd3'}}>{`Truth states: VERIFIED / PROBABLE / UNVERIFIED / CONFLICTED\nEvidence: E0–E5\nPublish: PUBLISH / PUBLISH_WITH_CAVEAT / EDIT_REQUIRED / HOLD / DO_NOT_PUBLISH / FAST_UNVERIFIED\nPipeline: Entity → Source → Evidence → Truth → Claim → Conflict → Risk → Rule Precedence → Editorial Gate → Recovery`}</pre></div>}
   {section==='sources'&&<div className="card"><h2>Sources</h2><div className="newsList">{['IGN','GameSpot','VGC','Gematsu','Eurogamer','PC Gamer','PlayStation Blog','Xbox Wire','Nintendo News','Steam News','SteamDB','SteamCharts','Metacritic','OpenCritic','Wario64'].map(x=><div className="story" key={x}><div className="storyTitle">{x}</div><div className="small">來源只是來源；帳號 ≠ 官方確認。Evidence hint 不等於最終信任評分。</div></div>)}</div></div>}
   {section==='settings'&&<div className="card"><h2>Settings</h2><p className="subtitle">Vercel 環境變數：OPENAI_API_KEY / OPENAI_MODEL。RSS 不需要 AI key；AI 功能未設定時會安全回報未配置。</p><p className="footerNote">下一階段接 Supabase 時，可把 sources、news、translations、claims、evidence、threads_drafts 與 audit_runs 分離儲存。</p></div>}
  </main>
 </div>
}
